sudo: required
language: python

python:
  - "3.6"
  - "3.7"

install:
  - pip install .
  - pip install -r requirements.txt

# Tests
script: nosetests

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9da87f9fb77e9c13620d
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
export PATH=$PATH:/home/vlopes/.gem/ruby/2.6.0/gems/travis-1.8.10/bin/